//go:build ignore

package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"go.mau.fi/util/exerrors"
)

const header = `// GENERATED BY internals_generate.go; DO NOT EDIT

//go:generate go run internals_generate.go
//go:generate goimports -local wa-api/internal/noise -w internals.go

package core

`
const postImportHeader = `
type DangerousInternalClient struct {
        c *Client
}

// DangerousInternals allows access to all unexported methods in Client.
//
// Deprecated: dangerous
func (cli *Client) DangerousInternals() *DangerousInternalClient {
        return &DangerousInternalClient{cli}
}

type DangerousInfoQuery = infoQuery
type DangerousInfoQueryType = infoQueryType

`

func getTypeName(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.Ident:
		return e.Name
	case *ast.StarExpr:
		return "*" + getTypeName(e.X)
	case *ast.ArrayType:
		if e.Len != nil {
			return fmt.Sprintf("[%s]%s", getTypeName(e.Len), getTypeName(e.Elt))
		}
		return "[]" + getTypeName(e.Elt)
	case *ast.MapType:
		return fmt.Sprintf("map[%s]%s", getTypeName(e.Key), getTypeName(e.Value))
	case *ast.ChanType:
		if e.Dir == ast.SEND {
			return fmt.Sprintf("chan<- %s", getTypeName(e.Value))
		} else if e.Dir == ast.RECV {
			return fmt.Sprintf("<-chan %s", getTypeName(e.Value))
		}
		return fmt.Sprintf("chan %s", getTypeName(e.Value))
	case *ast.FuncType:
		var params []string
		for _, param := range e.Params.List {
			params = append(params, getTypeName(param.Type))
		}
		var results []string
		if e.Results != nil {
			for _, result := range e.Results.List {
				results = append(results, getTypeName(result.Type))
			}
		}
		retVals := strings.Join(results, ", ")
		if len(results) > 1 {
			retVals = fmt.Sprintf("(%s)", retVals)
		}
		return fmt.Sprintf("func(%s) %s", strings.Join(params, ", "), retVals)
	case *ast.SelectorExpr:
		return fmt.Sprintf("%s.%s", getTypeName(e.X), e.Sel.Name)
	case *ast.StructType:
		// This isn't technically correct, but struct literals shouldn't be used for anything else
		return "struct{}"
	case *ast.Ellipsis:
		return fmt.Sprintf("...%s", getTypeName(e.Elt))
	case *ast.BasicLit:
		return e.Value
	default:
		panic(fmt.Errorf("unknown type %T", e))
	}
}

var write func(str string)
var writef func(format string, args ...any)

func main() {
	fset := token.NewFileSet()
	fileNames := sourceFileNames()
	files := make([]*ast.File, len(fileNames))
	for i, name := range fileNames {
		files[i] = exerrors.Must(parser.ParseFile(fset, name, nil, parser.SkipObjectResolution))
	}
	file := exerrors.Must(os.OpenFile("internals.go", os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0644))
	write = func(str string) {
		exerrors.Must(file.WriteString(str))
	}
	writef = func(format string, args ...any) {
		exerrors.Must(fmt.Fprintf(file, format, args...))
	}
	write(header)
	write("import (\n")
	for _, i := range mergedImports(files) {
		write("\t")
		if i.alias != "" {
			writef("%s ", i.alias)
		}
		writef("%s\n", i.path)
	}
	write(")\n")
	write(postImportHeader)
	for _, f := range files {
		processFile(f)
	}
	exerrors.PanicIfNotNil(file.Close())
}

// sourceFileNames devolve, em ordem determinada, todo .go de producao do
// pacote.
//
// Era uma lista literal de 32 nomes — os do upstream, de antes da divisao da
// raiz. Arquivos criados depois nunca entraram nela, entao o gerador so'
// enxergava 82 dos 197 metodos: rodar `go generate` derrubava 96 wrappers em
// silencio, sem erro de compilacao, porque DangerousInternals nao tem
// consumidor no repositorio (F29 em HOUSEKEEP.md).
//
// A varredura elimina a classe inteira do problema: nao ha mais lista para
// esquecer de atualizar.
func sourceFileNames() []string {
	all := exerrors.Must(filepath.Glob("*.go"))
	out := make([]string, 0, len(all))
	for _, name := range all {
		switch {
		case name == "internals.go", name == "internals_generate.go":
			// A saida do gerador e o proprio gerador.
			continue
		case strings.HasSuffix(name, "_test.go"):
			continue
		}
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}

type importSpec struct {
	alias string
	path  string
}

// mergedImports junta os imports de TODOS os arquivos processados.
//
// O gerador copiava apenas os imports de files[0]. Isso ja' era fragil, e
// virou quebra concreta quando assinaturas passaram a citar tipos de pacotes
// que files[0] nao importa (msgattrs.MessageAttrs, no adendo do F29): o
// internals.go saia com o tipo e sem o import, e desta vez o erro e' de
// compilacao, nao silencioso.
//
// A deduplicacao e' por caminho, mantendo o primeiro alias visto — dois
// arquivos do mesmo pacote nao podem dar aliases diferentes ao mesmo import
// sem que um deles ja' estivesse errado. Imports que sobrarem sem uso saem no
// `goimports` que o //go:generate roda logo depois.
func mergedImports(files []*ast.File) []importSpec {
	seen := map[string]importSpec{}
	for _, f := range files {
		for _, i := range f.Imports {
			if _, dup := seen[i.Path.Value]; dup {
				continue
			}
			spec := importSpec{path: i.Path.Value}
			if i.Name != nil {
				spec.alias = i.Name.Name
			}
			seen[i.Path.Value] = spec
		}
	}
	out := make([]importSpec, 0, len(seen))
	for _, spec := range seen {
		out = append(out, spec)
	}
	sort.Slice(out, func(a, b int) bool { return out[a].path < out[b].path })
	return out
}

// effectiveParamNames devolve, na ordem, o nome a usar para cada parametro do
// metodo — trocando o identificador branco por um nome sintetizado.
//
// O gerador copiava os nomes verbatim nos dois lugares onde eles aparecem: a
// assinatura do wrapper e a chamada ao metodo original. Para um parametro
// chamado `_` a assinatura fica valida, mas a chamada vira
// `int.c.decryptBotMessage(_, ...)`, que nao compila. So' apareceu quando a
// varredura de diretorio (F29) passou a alcancar metodos que usam `_` para
// marcar parametros ignorados.
//
// Os nomes sintetizados sao posicionais (arg0, arg1...) para que assinatura e
// chamada concordem por construcao — as duas passam por esta mesma lista.
func effectiveParamNames(funcDecl *ast.FuncDecl) []string {
	var out []string
	for _, param := range funcDecl.Type.Params.List {
		for _, name := range param.Names {
			if name.Name == "_" {
				out = append(out, fmt.Sprintf("arg%d", len(out)))
				continue
			}
			out = append(out, name.Name)
		}
	}
	return out
}

func processFile(f *ast.File) {
	ast.Inspect(f, func(node ast.Node) (retVal bool) {
		retVal = true
		funcDecl, ok := node.(*ast.FuncDecl)
		if !ok || funcDecl.Name.IsExported() {
			return
		}
		if funcDecl.Recv == nil || len(funcDecl.Recv.List) == 0 || len(funcDecl.Recv.List[0].Names) == 0 ||
			funcDecl.Recv.List[0].Names[0].Name != "cli" {
			return
		}
		paramNames := effectiveParamNames(funcDecl)
		writef("\nfunc (int *DangerousInternalClient) %s%s(", strings.ToUpper(funcDecl.Name.Name[0:1]), funcDecl.Name.Name[1:])
		next := 0
		for i, param := range funcDecl.Type.Params.List {
			if i != 0 {
				write(", ")
			}
			for j := range param.Names {
				if j != 0 {
					write(", ")
				}
				write(paramNames[next])
				next++
			}
			if len(param.Names) > 0 {
				write(" ")
			}
			write(getTypeName(param.Type))
		}
		write(") ")
		if funcDecl.Type.Results != nil && len(funcDecl.Type.Results.List) > 0 {
			needsParentheses := len(funcDecl.Type.Results.List) > 1 || len(funcDecl.Type.Results.List[0].Names) > 0
			if needsParentheses {
				write("(")
			}
			for i, result := range funcDecl.Type.Results.List {
				if i != 0 {
					write(", ")
				}
				for j, name := range result.Names {
					if j != 0 {
						write(", ")
					}
					write(name.Name)
				}
				if len(result.Names) > 0 {
					write(" ")
				}
				write(getTypeName(result.Type))
			}
			if needsParentheses {
				write(")")
			}
			write(" ")
		}
		write("{\n\t")
		if funcDecl.Type.Results != nil {
			write("return ")
		}
		writef("int.c.%s(", funcDecl.Name.Name)
		next = 0
		for i, param := range funcDecl.Type.Params.List {
			for j := range param.Names {
				if i != 0 || j != 0 {
					write(", ")
				}
				write(paramNames[next])
				next++
				if _, isEllipsis := param.Type.(*ast.Ellipsis); isEllipsis {
					write("...")
				}
			}
		}
		write(")\n}\n")
		return
	})
}
