#!/usr/bin/env bash
# Trava o teto de 300 linhas por arquivo de producao na raiz do pacote
# internal/wa-noise/ (ADR-0004: o diretorio deixou de ser espelho drift-zero e
# passou a seguir os mesmos pilares do resto do wa-api).
#
# Por que um script e nao um _test.go: internal/wa-noise/ esta fora de
# TEST_PKGS/COVER_PKGS/LINT_TARGETS no Makefile (ver .logcov-exclude e o
# racional em HOUSEKEEP.md), entao um teste Go dentro do pacote nunca seria
# executado por `make check`. Este gate roda sempre, no mesmo lugar em que
# waclient-license-check e waclient-drift ja rodam.
#
# Escopo: Fase A (raiz de internal/wa-noise/ e socket/), Fase B (appstate/,
# store/ e store/sqlstore/) e Fase C (binary/ com seu token/, types/ com
# types/events/, e os cinco subpacotes de util/) e Fase D (msgpad/, paircrypto/
# e msgattrs/, extraidos da raiz) e Fase F/G (media/, newsletter/ e
# appstatesync/, prekeys/, pairing/, tctoken/, notification/, retry/, group/,
# user/, send/ e message/, extracao real).
# Cobre o fork.
#
# Dois diretorios ficam de fora, ambos por serem codigo GERADO, pelo mesmo
# racional que o ADR-0004 aplica a proto/: dividi-los nao tem valor porque o
# gerador os recria.
#
#   internal/wa-noise/proto/            (protoc)
#   internal/wa-noise/binary/proto/     (generatelegacy.sh)
#
# O binary/proto/ merece nota: o cabecalho dele diz "DO NOT MODIFY: Generated
# by generatelegacy.sh", em caixa mista, entao a checagem de EXCLUDE_GENERATED
# abaixo (que procura "GENERATED BY" em maiusculas) nao o pegaria. Ele fica
# fora por nao estar em DIRS, que e' explicito e nao recursivo.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

DIRS="internal/wa-noise \
internal/wa-noise/msgpad \
internal/wa-noise/paircrypto \
internal/wa-noise/msgattrs \
internal/wa-noise/media \
internal/wa-noise/newsletter \
internal/wa-noise/appstatesync \
internal/wa-noise/prekeys \
internal/wa-noise/pairing \
internal/wa-noise/tctoken \
internal/wa-noise/notification \
internal/wa-noise/retry \
internal/wa-noise/group \
internal/wa-noise/user \
internal/wa-noise/send \
internal/wa-noise/message \
internal/wa-noise/handshake \
internal/wa-noise/keepalive \
internal/wa-noise/proxyconf \
internal/wa-noise/socket \
internal/wa-noise/appstate \
internal/wa-noise/store \
internal/wa-noise/store/sqlstore \
internal/wa-noise/binary \
internal/wa-noise/binary/token \
internal/wa-noise/types \
internal/wa-noise/types/events \
internal/wa-noise/security/cbc \
internal/wa-noise/security/gcm \
internal/wa-noise/security/hkdf \
internal/wa-noise/security/keys \
internal/wa-noise/observability/log"
MAX_LINES=300

# internals.go e' gerado por internals_generate.go ("GENERATED BY ...; DO NOT
# EDIT"). Pelo mesmo racional que o ADR-0004 usa para proto/, codigo gerado
# fica fora do teto: dividi-lo nao tem valor porque o gerador o recria.
EXCLUDE_GENERATED="internals.go"

fail=0
total=0

for dir in $DIRS; do
  checked=0
  for f in "$dir"/*.go; do
    base="$(basename "$f")"
    case "$base" in
      *_test.go) continue ;;
      "$EXCLUDE_GENERATED") continue ;;
    esac
    if head -1 "$f" | grep -q "GENERATED BY"; then
      continue
    fi
    checked=$((checked + 1))
    lines="$(wc -l < "$f" | tr -d ' ')"
    if [ "$lines" -gt "$MAX_LINES" ]; then
      echo "FALHA: $f tem $lines linhas (teto $MAX_LINES, ADR-0004)."
      fail=1
    fi
  done
  if [ "$checked" -eq 0 ]; then
    echo "FALHA: nenhum arquivo .go de producao encontrado em $dir/ — escopo do gate quebrou."
    exit 1
  fi
  total=$((total + checked))
done

dir_count="$(echo $DIRS | wc -w | tr -d ' ')"
echo "waclient-filesize-check: $total arquivos .go de producao em $dir_count diretorios de internal/wa-noise/ dentro do teto de $MAX_LINES linhas."

exit "$fail"
