package main

// extra_test.go — as formas menos comuns de cada regra, e os caminhos de erro
// da ferramenta. A fase exige >=97% de cobertura do proprio cmd/logcov: codigo
// novo abaixo de 95% corroi a margem que o plano gasta.

import (
	"errors"
	"go/ast"
	"go/token"
	"go/types"
	"os"
	"os/exec"
	"strings"
	"testing"

	"golang.org/x/tools/go/packages"
)

func TestX4PorAssinatura(t *testing.T) {
	entries := analyzeCase(t, "extra", nil)
	for _, k := range []string{"Doc.MarshalJSON", "Doc.UnmarshalJSON", "Doc.Format"} {
		if e := lookup(t, entries, casesPrefix+"extra."+k); e.Excluded != "X4" {
			t.Errorf("%s: Excluded = %q, quero X4", k, e.Excluded)
		}
	}
	if e := lookup(t, entries, casesPrefix+"extra.Doc.MarshalJSONish"); e.Excluded == "X4" {
		t.Error("MarshalJSONish nao tem a assinatura de X4 e nao pode ser excluida por ela")
	}
}

func TestX6ConcorrenciaESyncOnce(t *testing.T) {
	entries := analyzeCase(t, "extra", nil)
	for _, k := range []string{"Group.func1", "Once.func1", "OnceVal.func1", "GoIndirect.func1"} {
		if e := lookup(t, entries, casesPrefix+"extra."+k); e.Excluded != "" {
			t.Errorf("%s: Excluded = %q, quero elegivel", k, e.Excluded)
		}
	}
}

func TestSConsumePorSwitch(t *testing.T) {
	entries := analyzeCase(t, "extra", nil)
	if s := lookup(t, entries, casesPrefix+"extra.SwitchConsume").status(); !strings.Contains(s, "S-consume") {
		t.Errorf("SwitchConsume: status = %q, quero um S-consume", s)
	}
	if s := lookup(t, entries, casesPrefix+"extra.SwitchPropagate").status(); strings.Contains(s, "S-consume") {
		t.Errorf("SwitchPropagate propaga err e nao pode gerar S-consume: %q", s)
	}
}

func TestRaizDeCadeiaPorTipo(t *testing.T) {
	entries := analyzeCase(t, "extra", nil)
	for _, k := range []string{"Doc.LogValue", "Doc.LogPointer"} {
		e := lookup(t, entries, casesPrefix+"extra."+k)
		if !e.L1 {
			t.Errorf("%s: cadeia sobre zerolog.Logger deveria satisfazer L1", k)
		}
	}
	if e := lookup(t, entries, casesPrefix+"extra.NotALog"); e.L1 {
		t.Error("NotALog: .Info().Msg() sobre tipo alheio nao e' log reconhecido")
	}
}

func TestPropagacaoEDescarte(t *testing.T) {
	entries := analyzeCase(t, "extra", nil)
	if s := lookup(t, entries, casesPrefix+"extra.JoinPropagates").status(); strings.Contains(s, "S-ret") {
		t.Errorf("errors.Join encadeia a causa: %q", s)
	}
	if s := lookup(t, entries, casesPrefix+"extra.UnknownConstructor").status(); !strings.Contains(s, "S-ret") {
		t.Errorf("apperr.New sem causa descarta e deveria ficar descoberto: %q", s)
	}
}

func TestSHTTPFormas(t *testing.T) {
	entries := analyzeCase(t, "extra", nil)
	if s := lookup(t, entries, casesPrefix+"extra.HTTPError").status(); !strings.Contains(s, "S-http") {
		t.Errorf("http.Error com 418 deveria ser S-http: %q", s)
	}
	if s := lookup(t, entries, casesPrefix+"extra.NoStatusHelper").status(); strings.Contains(s, "S-http") {
		t.Errorf("WriteHeader(200) nao e' caminho de saida: %q", s)
	}
}

func TestParametrosSemNomeEReceiverGenerico(t *testing.T) {
	entries := analyzeCase(t, "extra", nil)
	lookup(t, entries, casesPrefix+"extra.Unnamed")
	lookup(t, entries, casesPrefix+"extra.Anonimo")
	lookup(t, entries, casesPrefix+"extra.Bag.Add")
}

// TestArquivoGeradoSaiDoEscopo — `// Code generated ... DO NOT EDIT.` remove o
// arquivo inteiro do universo.
func TestArquivoGeradoSaiDoEscopo(t *testing.T) {
	entries := analyzeCase(t, "generated", nil)
	if len(entries) != 0 {
		t.Fatalf("arquivo gerado deveria sair do universo, veio %d entradas", len(entries))
	}
}

func TestIsGeneratedNegativo(t *testing.T) {
	file := &ast.File{Comments: []*ast.CommentGroup{{List: []*ast.Comment{
		{Text: "// Code generated by algo"},
		{Text: "// comum"},
	}}}}
	if isGenerated(file) {
		t.Error("comentario sem o sufixo DO NOT EDIT. nao marca arquivo gerado")
	}
}

func TestIsAccessorOperandFormas(t *testing.T) {
	p := &pkgCtx{}
	cases := []struct {
		expr ast.Expr
		want bool
	}{
		{&ast.BasicLit{Kind: token.INT, Value: "1"}, true},
		{&ast.Ident{Name: "x"}, true},
		{&ast.SelectorExpr{X: &ast.Ident{Name: "b"}, Sel: &ast.Ident{Name: "f"}}, true},
		{&ast.SelectorExpr{X: &ast.Ident{Name: "outro"}, Sel: &ast.Ident{Name: "f"}}, false},
		{&ast.SelectorExpr{X: &ast.CallExpr{}, Sel: &ast.Ident{Name: "f"}}, false},
		{&ast.StarExpr{X: &ast.Ident{Name: "x"}}, true},
		{&ast.UnaryExpr{Op: token.AND, X: &ast.Ident{Name: "x"}}, true},
		{&ast.UnaryExpr{Op: token.SUB, X: &ast.Ident{Name: "x"}}, false},
		{&ast.CallExpr{}, false},
	}
	for i, c := range cases {
		if got := isAccessorOperand(p, c.expr, "b"); got != c.want {
			t.Errorf("caso %d: got %v, quero %v", i, got, c.want)
		}
	}
}

func TestReceiverNameSemReceiver(t *testing.T) {
	if got := receiverName(nil); got != "" {
		t.Errorf("receiverName(nil) = %q", got)
	}
	if got := receiverName(&ast.FuncDecl{}); got != "" {
		t.Errorf("receiverName(sem recv) = %q", got)
	}
	fd := &ast.FuncDecl{Recv: &ast.FieldList{List: []*ast.Field{{Type: &ast.Ident{Name: "T"}}}}}
	if got := receiverName(fd); got != "" {
		t.Errorf("receiverName(recv anonimo) = %q", got)
	}
}

func TestTypeExprNameFormas(t *testing.T) {
	cases := map[string]ast.Expr{
		"T": &ast.StarExpr{X: &ast.Ident{Name: "T"}},
		"G": &ast.IndexExpr{X: &ast.Ident{Name: "G"}},
		"H": &ast.IndexListExpr{X: &ast.Ident{Name: "H"}},
		"?": &ast.CallExpr{},
	}
	for want, expr := range cases {
		if got := typeExprName(expr); got != want {
			t.Errorf("typeExprName = %q, quero %q", got, want)
		}
	}
}

func TestParamNamesSemParametros(t *testing.T) {
	if got := paramNames(nil); got != nil {
		t.Errorf("paramNames(nil) = %v", got)
	}
	if got := paramNames(&ast.FuncDecl{Type: &ast.FuncType{}}); got != nil {
		t.Errorf("paramNames(sem params) = %v", got)
	}
}

func TestImplementsNulos(t *testing.T) {
	a := &analysis{}
	if a.implements(nil, nil) {
		t.Error("implements(nil, nil) deveria ser false")
	}
}

func TestRuleL3PortaEZerolog(t *testing.T) {
	if !ruleL3Structured(logSite{form: "port", fields: 2}) {
		t.Error("porta com 2 keyvals pares deveria passar")
	}
	if ruleL3Structured(logSite{form: "port", fields: 3, odd: true}) {
		t.Error("porta com keyvals impar deveria reprovar")
	}
	if ruleL3Structured(logSite{form: "zerolog"}) {
		t.Error("zerolog sem campo deveria reprovar")
	}
}

func TestRuleX5PrefixoExato(t *testing.T) {
	a := &analysis{excludes: []string{"cmd/"}}
	if !ruleX5PackageExcluded(a, "cmd") {
		t.Error("o proprio diretorio listado deve ser excluido")
	}
	if !ruleX5PackageExcluded(a, "cmd/logcov") {
		t.Error("subpacote deve ser excluido")
	}
	if ruleX5PackageExcluded(a, "cmdx/outra") {
		t.Error("prefixo parcial nao pode excluir")
	}
}

// --- caminhos de erro da ferramenta ---

type escritorQuebrado struct{}

func (escritorQuebrado) Write([]byte) (int, error) { return 0, errors.New("disco cheio") }

func TestEmissoresPropagamErroDeEscrita(t *testing.T) {
	a := newAnalysis("../..", "wa-api", nil, nil)
	pkgs, err := a.load("./" + casesPrefix + "l2")
	if err != nil {
		t.Fatal(err)
	}
	rep := a.Analyze(pkgs)
	if err := emitGolden(rep, escritorQuebrado{}); err == nil {
		t.Error("emitGolden deveria propagar erro de escrita")
	}
	if err := emitUncovered(rep, escritorQuebrado{}); err == nil {
		t.Error("emitUncovered deveria propagar erro de escrita")
	}
	if err := emitByPackage(rep, escritorQuebrado{}); err == nil {
		t.Error("emitByPackage deveria propagar erro de escrita")
	}
	if err := emitSummary(rep, escritorQuebrado{}); err == nil {
		t.Error("emitSummary deveria propagar erro de escrita")
	}
	if err := emitBudget(rep, escritorQuebrado{}); err == nil {
		t.Error("emitBudget deveria propagar erro de escrita")
	}
	if err := emitJSON(rep, escritorQuebrado{}); err == nil {
		t.Error("emitJSON deveria propagar erro de escrita")
	}
}

func TestMeasureForaDeModulo(t *testing.T) {
	if _, _, err := measure(&options{root: t.TempDir(), patterns: []string{"./pkg/..."}}); err == nil {
		t.Fatal("medir fora de um modulo deveria falhar")
	}
}

func TestLoadComPacoteInexistente(t *testing.T) {
	a := newAnalysis("../..", "wa-api", nil, nil)
	if _, err := a.load("./cmd/logcov/testdata/cases/nao-existe"); err == nil {
		t.Fatal("pacote inexistente deveria falhar")
	}
}

// TestMainViaSubprocesso — `main` so' delega para run; o unico jeito honesto de
// cobri-la e' executando o binario de verdade.
func TestMainViaSubprocesso(t *testing.T) {
	if os.Getenv("LOGCOV_SUBPROCESSO") == "1" {
		os.Args = []string{"logcov", "-flag-que-nao-existe"}
		main()
		return
	}
	cmd := exec.Command(os.Args[0], "-test.run=TestMainViaSubprocesso")
	cmd.Env = append(os.Environ(), "LOGCOV_SUBPROCESSO=1")
	err := cmd.Run()
	var exitErr *exec.ExitError
	if !errors.As(err, &exitErr) {
		t.Fatalf("main deveria sair com codigo != 0, deu %v", err)
	}
}

// --- leitura de configuracao: formas e caminhos de erro ---

func TestReadExcludeFileNormalizaEIgnora(t *testing.T) {
	dir := t.TempDir()
	path := dir + "/.logcov-exclude"
	conteudo := "# comentario\n\ncmd\npkg/infra/messaging/\n"
	if err := os.WriteFile(path, []byte(conteudo), 0o600); err != nil {
		t.Fatal(err)
	}
	got, err := readExcludeFile(path)
	if err != nil {
		t.Fatal(err)
	}
	want := []string{"cmd/", "pkg/infra/messaging/"}
	if len(got) != len(want) || got[0] != want[0] || got[1] != want[1] {
		t.Fatalf("excludes = %v, quero %v", got, want)
	}
	if _, err := readExcludeFile(dir); err == nil {
		t.Error("ler um diretorio como lista de exclusao deveria falhar")
	}
}

func TestReadDepguardDirsFormas(t *testing.T) {
	dir := t.TempDir()
	path := dir + "/.golangci.yml"
	yml := `linters:
  settings:
    depguard:
      rules:
        camada-de-aplicacao:
          nota: linha entre a regra e files
          files:
            - "**/pkg/application/usecase/chat/*.go"
            - "**/pkg/application/contracts/**"
          deny:
            - pkg: github.com/rs/zerolog
`
	if err := os.WriteFile(path, []byte(yml), 0o600); err != nil {
		t.Fatal(err)
	}
	got, err := readDepguardDirs(path)
	if err != nil {
		t.Fatal(err)
	}
	want := []string{"pkg/application/contracts", "pkg/application/usecase/chat"}
	if len(got) != len(want) || got[0] != want[0] || got[1] != want[1] {
		t.Fatalf("dirs = %v, quero %v", got, want)
	}
	if _, err := readDepguardDirs(dir); err == nil {
		t.Error("ler um diretorio como .golangci.yml deveria falhar")
	}
}

func TestCountExemptAnnotationsEmArquivoIlegivel(t *testing.T) {
	dir := t.TempDir()
	sub := dir + "/proibido"
	if err := os.Mkdir(sub, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(sub+"/a.go", []byte("//log:exempt teste\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	n, err := countExemptAnnotations(dir)
	if err != nil || n != 1 {
		t.Fatalf("countExemptAnnotations = (%d, %v), quero (1, nil)", n, err)
	}
	if err := os.Chmod(sub, 0o000); err != nil {
		t.Skip("nao consigo revogar permissao neste ambiente")
	}
	defer func() { _ = os.Chmod(sub, 0o755) }()
	if _, err := countExemptAnnotations(dir); err == nil {
		t.Skip("o walk conseguiu ler mesmo sem permissao (provavelmente root)")
	}
}

func TestMeasureComExcludeInvalido(t *testing.T) {
	dir := t.TempDir()
	if err := os.Mkdir(dir+"/.logcov-exclude", 0o755); err != nil {
		t.Fatal(err)
	}
	if _, _, err := measure(&options{root: dir, patterns: []string{"./..."}}); err == nil {
		t.Fatal("exclude invalido deveria falhar")
	}
	if err := os.Mkdir(dir+"/.golangci.yml", 0o755); err != nil {
		t.Fatal(err)
	}
	_ = os.Remove(dir + "/.logcov-exclude")
	if _, _, err := measure(&options{root: dir, patterns: []string{"./..."}}); err == nil {
		t.Fatal("golangci.yml invalido deveria falhar")
	}
}

// TestMeasureAbortaComDepguardVazio — R5: se .golangci.yml existe mas
// readDepguardDirs nao extrai nenhum diretorio (o parsing linha-a-linha
// quebrou, ou a regra camada-de-aplicacao mudou de forma), measure ABORTA em
// vez de continuar silenciosamente com a restricao L1-b desativada — o mesmo
// padrao de fail-closed ja usado para a porta contracts.Logger.
func TestMeasureAbortaComDepguardVazio(t *testing.T) {
	dir := t.TempDir()
	yml := "linters:\n  settings:\n    depguard:\n      rules: {}\n"
	if err := os.WriteFile(dir+"/.golangci.yml", []byte(yml), 0o600); err != nil {
		t.Fatal(err)
	}
	_, _, err := measure(&options{root: dir, patterns: []string{"./..."}})
	if err == nil || !strings.Contains(err.Error(), "camada-de-aplicacao") {
		t.Fatalf("erro = %v, quero abortar por depguard vazio com .golangci.yml presente", err)
	}
}

// TestMeasureAbortaSemPorta — se contracts.Logger nao entrar no grafo, a
// ferramenta ABORTA. Reportar zero seria indistinguivel de um repositorio sem
// log (criterio 9.3).
func TestMeasureAbortaSemPorta(t *testing.T) {
	_, _, err := measure(&options{root: "../..", patterns: []string{"./" + casesPrefix + "generated"}})
	if err == nil || !strings.Contains(err.Error(), "contracts.Logger") {
		t.Fatalf("erro = %v, quero abortar por porta nao resolvida", err)
	}
}

func TestParseCoverProfileLinhaVazia(t *testing.T) {
	blocks, err := parseCoverProfile(strings.NewReader("mode: set\n\nf.go:1.1,2.1 3 0\n\nf.go:1.1,2.1 3 5\n"))
	if err != nil {
		t.Fatal(err)
	}
	_, total, covered := aggregateCoverage(blocks)
	if total != 3 || covered != 3 {
		t.Fatalf("dedup por max(count): total=%d covered=%d, quero 3 e 3", total, covered)
	}
}

func TestEmitBudgetSemCaminhosDescobertos(t *testing.T) {
	a := newAnalysis("../..", "wa-api", nil, nil)
	pkgs, err := a.load("./" + casesPrefix + "l1")
	if err != nil {
		t.Fatal(err)
	}
	var buf strings.Builder
	if err := emitBudget(a.Analyze(pkgs), &buf); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(buf.String(), "caminhos de saida descobertos") {
		t.Fatal("orcamento sem a secao de caminhos")
	}
}

// --- guardas defensivas das regras, exercitadas sem carregar pacote ---

func novoCtx(tipos map[ast.Expr]types.TypeAndValue) *pkgCtx {
	return &pkgCtx{
		a:    &analysis{},
		info: &types.Info{Types: tipos, Defs: map[*ast.Ident]types.Object{}},
	}
}

func TestIsHandlerShapedFuncLitGuardas(t *testing.T) {
	lit := &ast.FuncLit{}
	p := novoCtx(map[ast.Expr]types.TypeAndValue{})
	if isHandlerShapedFuncLit(p, lit) {
		t.Error("literal sem tipo resolvido nao pode ser handler")
	}
	sig := types.NewSignatureType(nil, nil, nil, types.NewTuple(), types.NewTuple(), false)
	p = novoCtx(map[ast.Expr]types.TypeAndValue{lit: {Type: sig}})
	if isHandlerShapedFuncLit(p, lit) {
		t.Error("sem http.Handler resolvido nao ha' forma de handler")
	}
}

func TestRuleX4SemDefinicao(t *testing.T) {
	fd := &ast.FuncDecl{Name: ast.NewIdent("String")}
	if ruleX4SelfReferential(novoCtx(nil), fd) {
		t.Error("sem objeto resolvido X4 nao pode disparar")
	}
	if ruleX4SelfReferential(novoCtx(nil), nil) {
		t.Error("FuncDecl nil nao pode disparar X4")
	}
}

func TestTupleMatchesTiposDiferentes(t *testing.T) {
	tup := types.NewTuple(types.NewVar(0, nil, "x", types.Typ[types.Int]))
	if tupleMatches(tup, []string{"string"}) {
		t.Error("tipos diferentes nao podem casar")
	}
	if tupleMatches(tup, nil) {
		t.Error("aridades diferentes nao podem casar")
	}
	if !tupleMatches(tup, []string{"int"}) {
		t.Error("tipos iguais deveriam casar")
	}
}

func TestRuleL1bcChainNaoSelector(t *testing.T) {
	call := &ast.CallExpr{Fun: ast.NewIdent("f")}
	if _, ok := ruleL1bcChain(novoCtx(nil), call); ok {
		t.Error("chamada que nao e' selector nao e' cadeia de log")
	}
	if _, ok := ruleL1aPort(novoCtx(nil), call); ok {
		t.Error("chamada que nao e' selector nao e' porta")
	}
}

func TestChainRootFormGuardas(t *testing.T) {
	p := novoCtx(nil)
	if _, ok := chainRootForm(p, &ast.BasicLit{}); ok {
		t.Error("literal nao e' raiz de cadeia")
	}
	if rootIsHlogFromRequest(p, &ast.CallExpr{Fun: ast.NewIdent("f")}) {
		t.Error("chamada sem selector nao e' hlog.FromRequest")
	}
}

func TestLookupInterfaceAusente(t *testing.T) {
	pkg := types.NewPackage("exemplo", "exemplo")
	pkg.MarkComplete()
	if got := lookupInterface(&packages.Package{Types: pkg}, "NaoExiste"); got != nil {
		t.Errorf("lookupInterface = %v, quero nil", got)
	}
}

func TestWriteCoverageReportPerfilInvalido(t *testing.T) {
	path := t.TempDir() + "/ruim.out"
	if err := os.WriteFile(path, []byte("mode: set\nlixo\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	var buf strings.Builder
	if err := writeCoverageReport(path, &buf); err == nil {
		t.Fatal("perfil invalido deveria falhar")
	}
}
